server:
  port: ${SERVER_PORT:1234}

spring:
  application:
    name: team2

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
